version: '3.1'
services:
  court-booking:
    image: 'court-booking:0.0.1-SNAPSHOT'
    deploy:
      resources:
        limits:
          memory: 700MB
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=passw0rd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
  db:
    image: postgres
    deploy:
      resources:
        limits:
          memory: 300MB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=passw0rd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5